### PR TITLE
Several enhancements and fixes

### PR DESCRIPTION
**Pull request by radokristof**
I have added translations to the module. Now it should be easier to localize everything. One thing I have found is the "Last update" string. 
However for example we could add a default formatting for every language for `nextTransitVehicleDepartureFormat`.

Also made some styling and other code fixes.

### CODE REVIEW

**Comment by qistoph** [comment]
Thanks for the PR. I've merged part of it, because I didn't like removing the `startTime` and `endTime`, since people might be using that.

**Comment by radokristof** [comment]
@qistoph I just thought it is a duplicate feature. You can hide every destination with setting each startTime and endTime. 

I'm still investigating the module not appearing issue. Did you had this before?

**Comment by qistoph** [comment]
I have seen it in the past, but seemed to have that issue fixed. It wouldn't show on my mirror every morning when waking up from stand-by. Now it's there every morning.

**Comment by radokristof** [comment]
@qistoph Thanks! For me it now seems 50-50%. Today it appeared in the morning, yesterday not... 
I will add more logging temporary for me and see if I can get any assumption why it is not working.
One thing I can think of is that something interrupts the waiting thread and it stops completely.
How many destination have you set up?

**Comment by qistoph** [comment]
Currently just 2. One driving and one public transport.

**Comment by radokristof** [comment]
I have 4 in the weekdays and 2 in the weekends... It seemed that it will do this when there is more than 2... I will use the next week to troubleshoot this.

**Pull request closed without merging**
